### ISSUE TITLE
Subclass Compatibility Framework Status

### ISSUE THREAD

**Issue by NellsRelo** [BG3-Community-Library-Team/BG3-Community-Library#43]
This is less of an issue and more of an informative ticket, to track the known Subclass mods. Unchecked means "Waiting on Permission, while Checked means "We have permission":

### Barbarian
- [ ] [Path of the Giant - Barbarian Subclass](https://www.nexusmods.com/baldursgate3/mods/1806?tab=description) by [Sewinlife](https://www.nexusmods.com/baldursgate3/users/5152522)
- [ ] [Path of the Crusher](https://www.nexusmods.com/baldursgate3/mods/1858) by [Colten88](https://www.nexusmods.com/baldursgate3/users/26603939)

### Bard
- [x] [Bard Subclass - College of Glamour](https://www.nexusmods.com/baldursgate3/mods/741) by [Bonebreaker687](https://www.nexusmods.com/baldursgate3/users/9228502)
- [ ] [College of Players Bard Homebrew Subclass](https://www.nexusmods.com/baldursgate3/mods/909) by [DroZzhat](https://www.nexusmods.com/baldursgate3/users/172568)

### Cleric
- [X] [Cleric Subclasses - Release](https://www.nexusmods.com/baldursgate3/mods/432) by [baltavi](https://www.nexusmods.com/baldursgate3/users/6366410)
- [x] [Death Domain Subclass for Cleric](https://www.nexusmods.com/baldursgate3/mods/1552) by [CrackerJackGCO](https://www.nexusmods.com/baldursgate3/users/85819)

### Druid
- [X] [Circle of Dreams](https://www.nexusmods.com/baldursgate3/mods/1844) by [Kingdomyoshi](https://www.nexusmods.com/baldursgate3/users/27186944)

### Fighter
- [X] [Diamon's Mystic Manual - Fighter Subclasses](https://www.nexusmods.com/baldursgate3/mods/1599) by [Backburner26](https://www.nexusmods.com/baldursgate3/users/19603604)
- [X] [Marksman - Fighter's Subclass](https://www.nexusmods.com/baldursgate3/mods/1278) by [afftor](https://www.nexusmods.com/baldursgate3/users/968899)
- [x] [Arcane Archer - Subclass](https://www.nexusmods.com/baldursgate3/mods/1747/) by [ShivasShadow](https://www.nexusmods.com/baldursgate3/users/94470308)

### Monk
 - [X] [Way of the Drunken Master](https://www.nexusmods.com/baldursgate3/mods/1832) by [JohnnyTheSneeder](https://www.nexusmods.com/baldursgate3/users/188742234)
- [X] [Monk Subclass -- Way of the Kensei](https://www.nexusmods.com/baldursgate3/mods/1330) by [YuukaYunna](https://www.nexusmods.com/baldursgate3/users/45490107)
- [X] [Way of the Sun Soul (Monk Subclass](https://www.nexusmods.com/baldursgate3/mods/1467) by [Kingdomyoshi](https://www.nexusmods.com/baldursgate3/users/27186944)
- [X] [Way of Mercy](https://www.nexusmods.com/baldursgate3/mods/1749) by [PlatypusVenom](https://www.nexusmods.com/users/159098228)

### Paladin
- [ ] [Oath of Conquest](https://www.nexusmods.com/baldursgate3/mods/477) by [havsglimt](https://www.nexusmods.com/baldursgate3/users/77184368)

### Ranger
_No known Subclasses_

### Rogue
- [x] [Inquisitive (Rogue Subclass](https://www.nexusmods.com/baldursgate3/mods/1728) by [Kingdomyoshi](https://www.nexusmods.com/baldursgate3/users/27186944)
- [x] [Mastermind (Rogue Subclass](https://www.nexusmods.com/baldursgate3/mods/1611) by [Kingdomyoshi](https://www.nexusmods.com/baldursgate3/users/27186944)
- [x] [Rogues Extra Fullgameready](https://www.nexusmods.com/baldursgate3/mods/189) by [lostoulman](https://www.nexusmods.com/baldursgate3/users/55895062)
- [x] [Swashbuckler](https://www.nexusmods.com/baldursgate3/mods/507) by [wesslen](https://www.nexusmods.com/baldursgate3/users/89809)

### Sorcerer
- [X] [Shadow Sorcerer - Subclass](https://www.nexusmods.com/baldursgate3/users/466538) by [Baaleos](https://www.nexusmods.com/baldursgate3/users/1111397)
- [ ] [Revised Sorcerer Subclasses (Divine Soul specifically)](https://www.nexusmods.com/baldursgate3/mods/1667?tab=description) by [pieroerri](https://www.nexusmods.com/baldursgate3/users/74325213)

### Warlock
- [X] [Celestial Warlock](https://www.nexusmods.com/baldursgate3/mods/1567) by [FluffyDragon24](https://www.nexusmods.com/baldursgate3/users/130905368)
- [X] [Hexblade Subclass](https://www.nexusmods.com/baldursgate3/mods/1100) by [Feriat111](https://www.nexusmods.com/baldursgate3/users/26820389)
- [X] [Necromancer Subclass for Warlock - Dread Overlord](https://www.nexusmods.com/baldursgate3/mods/394) by [dreadoverlord]( https://www.nexusmods.com/baldursgate3/users/88747523)

### Wizard
- [X] [Expansion (Bladesinger Only)](https://www.nexusmods.com/baldursgate3/mods/279) by [DiZ91981](https://www.nexusmods.com/baldursgate3/users/57776731)
- [X] [Sorcery Arcane Tradition (Full Release Ready)](https://www.nexusmods.com/baldursgate3/mods/446) by [fmsette](https://www.nexusmods.com/baldursgate3/users/129362963)
- [X] [Wizard Traditions - War Magic](https://www.nexusmods.com/baldursgate3/mods/924) by [fierrof](https://www.nexusmods.com/baldursgate3/users/466538)

**Comment by NellsRelo** [comment]
The release of BG3 Subclass Patcher makes the Subclass Compatibility Framework obsolete, allowing any user to patch their subclasses. In light of this, I'm thinking it may be best at this stage to split the Subclass Compatibility Patch into its own separate mod, which I'll continue to maintain as new classes are released (for players uncomfortable with using a tool), and bring Community Library back to a pure Modder's Resource, but open to thoughts.

**Comment by NellsRelo** [comment]
Moving discussion here: https://github.com/BG3-Community-Library-Team/BG3-Subclass-Compatibility-Framework/issues/1
